runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: '/service-worker.js'
    secure: always
    static_files: build/service-worker.js
    upload: build/service-worker.js
    mime_type: application/javascript

  - url: /(.*\.js)$
    secure: always
    static_files: build/\1
    upload: build/.*\.js$
    mime_type: application/javascript

  - url: /(.*\.(css|map|png|jpg|svg|ico|json|txt|woff))$
    secure: always
    static_files: build/\1
    upload: build/.*\.(css|map|png|jpg|svg|ico|json|txt|woff)$

  - url: '/(.*)'
    secure: always
    static_files: build/index.html
    upload: build/index.html

env_variables:
  PUBLIC_URL: https://delia-barraza-308508.wn.r.appspot.com
  NODE_ENV: production